lang: 'int'
url: "https://www.weeklyosm.eu/en/archives/{c.url_nr}/"
runnable: True
#do_mail: False     # uncomment in order to ignore "--mail" for this language
do_twitter: False   # comment to send an additional tweet in this language if "--twitter" is called (attention: shorten text to <280 chars!)
#do_mastodon: False # uncomment in order to ignore "--mastodon" for this language

mail_from: "weeklyteam <{c.mail_user}>"
mail_subject: 'weeklyOSM #{c.post_nr} {c.daterange_str}'
tw_text: "Issue {c.post_nr} of weeklyOSM is out ğŸš€ Lisez les derniÃ¨res nouvelles de l'univers #openstreetmap ğŸ—ºï¸ Viele Neuigkeiten aus der #osm Welt ğŸ“° æ–°ä¸€æœŸçš„OSMå‘¨åˆŠå·²ç»å‘å¸ƒ ğŸŒ Se ha publicado un nuevo nÃºmero delsemanarioOSM ğŸŒ æœ€æ–°ã®é€±åˆŠOSMãŒç™ºè¡Œã•ã‚Œã¾ã—ãŸã€‚Â  ğŸ’¬ ì£¼ê°„OSM ìµœì‹ í˜¸ê°€ ë‚˜ì™”ìŠµë‹ˆë‹¤ ğŸ‘‰ https://www.weeklyosm.eu/archives/{c.url_nr}"

mail_to: 
  - "you could enter emails directly here, but it can/will"
  - "be overwritten by content from mailto/weekly_en.yaml"
mail_body: | 
  The weekly round-up of OSM news, issue # {c.post_nr},
  is now available online, giving as always a summary of a lot of things happening in the openstreetmap world:
  
  https://www.weeklyosm.eu/archives/{c.url_nr}

  Enjoy! 

  Did you know that you can also submit messages for the weeklyOSM? Just log in to https://osmbc.openstreetmap.de/login with your OSM account. Read more about how to write a post here: https://www.weeklyosm.eu/this-news-should-be-in-weeklyosm 

  weeklyOSM? 
  who: https://wiki.openstreetmap.org/wiki/WeeklyOSM#Available_Languages 
  where?: https://umap.openstreetmap.fr/en/map/weeklyosm-is-currently-produced-in_56718#2/8.6/108.3
