lang: "uk"
runnable: True
#do_mail: False     # uncomment in order to ignore "--mail" for this language
#do_twitter: False  # uncomment in order to ignore "--twitter" for this language
#do_mastodon: False # uncomment in order to ignore "--mastodon" for this language
do_bluesky: False # comment to send an additional post in this language if "--bluesky" is called
do_josm: False # comment to send an additional josm wiki post in this language if "--josm" is called
mail_from: "weeklyteam <{c.mail_USER}>"
mail_subject: "Тижневик OSM № {c.post_nr} {c.daterange_str}"
tw_text:
    "Тижневик OSM № {c.post_nr} тепер доступний *Українською*. Це новини зі
    світу #openstreetmap #osm https://www.weeklyosm.eu/uk/archives/{c.url_nr}"
bluesky_text: "{c.tw_text}"
mail_body: |
    Щотижневий огляд новин OSM, випуск № {c.post_nr}, тепер доступний онлайн українською мовою, надаючи, як завжди, короткий опис багатьох подій, що відбуваються у світі openstreetmap:

     {c.url}

    Насолоджуйтесь! 
    Чи знаєте ви, що також можете надсилати повідомлення для weeklyOSM? Просто увійдіть на https://osmbc.openstreetmap.de/login за допомогою свого облікового запису OSM. Дізнайтеся більше про те, як написати допис тут: https://www.weeklyosm.eu/this-news-should-be-in-weeklyosm

    Тижневик weeklyOSM? 
    хто: https://wiki.openstreetmap.org/wiki/WeeklyOSM#Available_Languages 
    де?: https://umap.openstreetmap.fr/en/map/weeklyosm-is-currently-produced-in_56718#2/8.6/108.3
