---
lang: "it"
runnable: true
#do_mail: false     # uncomment in order to ignore "--mail" for this language
#do_twitter: false  # uncomment in order to ignore "--twitter" for this language
#do_mastodon: false # uncomment in order to ignore "--mastodon" for this language
do_bluesky: false # comment to send an additional post in this language if "--bluesky" is called
do_josm: false # comment to send an additional josm wiki post in this language if "--josm" is called
mail_from: "weeklyteam <{c.mail_USER}>"
mail_subject: "weeklyOSM #{c.post_nr} {c.daterange_str}"
tw_text:
    "Il numero {c.post_nr} del weeklyOSM è ora disponibile in Italiano. Le
    ultime notizie dal mondo #openstreetmap #osm
    https://www.weeklyosm.eu/it/archives/{c.url_nr}."
bluesky_text: "{c.tw_text}"
mail_body: |
    Il settimanale di notizie su OSM, numero # {c.post_nr}, è ora disponibile online in italiano,
    fornendo come sempre un riassunto di molte cose che accadono nel mondo OpenStreetMap:

    {c.url}

    Buona lettura!

    Sai che possono anche inviare messaggi per il weeklyOSM? Basta effettuare il login
    su https://osmbc.openstreetmap.de/login con il tuo account OSM.

    Per saperne di più su come scrivere un messaggio, leggi qui: https://www.weeklyosm.eu/this-news-should-be-in-weeklyosm
    weeklyOSM?

    chi: https://wiki.openstreetmap.org/wiki/WeeklyOSM#Available_Languages
    dove?: https://umap.openstreetmap.fr/en/map/weeklyosm-is-currently-produced-in_56718#2/8.6/108.3
