
lang: 'sw'
runnable: True
#do_mail: False    # uncomment in order to ignore "--mail" for this language
#do_twitter: False # uncomment in order to ignore "--twitter" for this language
do_mastodon: False # comment to send an additional toot in this language if "--mastodon" is callediert wird, wird der paramterer "--mastodon" ignoriert und NICHT getootet
mail_from: "weeklyteam <{c.mail_user}>"
mail_subject: 'OSMkilawiki #{c.post_nr} {c.daterange_str}'
tw_text: "OSMkilawiki, suala {c.post_nr}, sasa linapatikana kwenye mtandao katika lugha ya *Kiswahili*, kutupa muhtasari wa mambo yote yanayotokea katika ulimwengu wa #OpenStreetMap #OSM https://www.weeklyosm.eu/sw/archives/{c.url_nr}"
mail_body: | 
  Habari za OpenStreetMap, swala {c.post_nr}, sasa linapatikana kwenye mtandao katika lugha ya Kiswahili, kutupa muhtasari wa mambo yote yanayotokea katika ulimwengu wa OpenStreetMap: 
  
  {c.url}
  
  Furahia!
  
  OSMkilawiki? 
  uwe nani? https://wiki.openstreetmap.org/wiki/WeeklyOSM#Available_Languages
  uwe wapi? https://umap.openstreetmap.fr/en/map/weeklyosm-is-currently-produced-in_56718#2/8.6/108.3
