lang: 'tr'
runnable: True
#do_mail: False    # uncomment in order to ignore "--mail" for this language
#do_twitter: False # uncomment in order to ignore "--twitter" for this language
do_mastodon: False # comment to send an additional toot in this language if "--mastodon" is called
mail_from: "weeklyteam <{c.mail_user}>"
mail_subject: 'weeklyOSM #{c.post_nr} {c.daterange_str}'
tw_text: "weeklyOSM'in {c.post_nr}. hafta edisyonu, #openstreetmap #osm dünyasından haberlerle şimdi Türkçe https://www.weeklyosm.eu/tr/archives/{c.url_nr}"
mail_body: | 
 OSM ile ilgili haberlerin derlendiği ve OpenStreetMap dünyasındaki pek çok gelişmelerin paylaşıldığı haftalık bülten, {c.post_nr}. bölümüyle çevrimiçi ve Türkçe olarak erişilebilir durumda:
  
 {c.url}

 İyi okumalar! 

 weeklyOSM'e sizin de ekleme yapabileceğinizi biliyor muydunuz? Sadece https://osmbc.openstreetmap.de/login adresine OSM hesabınızla giriş yapın. Yeni bir haber yüklemek için yapmanız gerekenleri buradan öğrenebilirsiniz: https://www.weeklyosm.eu/this-news-should-be-in-weeklyosm 
 
 weeklyOSM? 
 Kim?: https://wiki.openstreetmap.org/wiki/WeeklyOSM#Available_Languages 
 Nerede?: https://umap.openstreetmap.fr/en/map/weeklyosm-is-currently-produced-in_56718#2/8.6/108.3
