---
context: "WEEKLYTEST"
lang: "ko"
runnable: true
url: "https://www.weeklyosm.eu/{c.lang}/archives/{c.url_nr}/"
do_mail: false
do_forum: false
do_twitter: true
do_mastodon: false
do_josm: false
#tw_text = "Die OpenStreetMap Wochennotiz Nr. {c.post_nr} ist da, wie immer mit allen Neuigkeiten aus der #openstreetmap #osm Welt: {c.url}"
tw_text:
    "#openstreetmap #osm 관련 뉴스를 전하는 주간OSM이 {c.post_nr}번째 기사를
    발행했습니다! https://www.weeklyosm.eu/archives/{c.url_nr}"
