---
lang: "ko"
runnable: true
#do_mail: false     # uncomment in order to ignore "--mail" for this language
#do_twitter: false  # uncomment in order to ignore "--twitter" for this language
#do_mastodon: false # uncomment in order to ignore "--mastodon" for this language
do_bluesky: false # comment to send an additional post in this language if "--bluesky" is called
do_josm: false # comment to send an additional josm wiki post in this language if "--josm" is called
mail_from: "weeklyteam <{c.mail_USER}>"
mail_subject: "weeklyOSM #{c.post_nr} {c.daterange_str}"
tw_text:
    "#openstreetmap #osm 관련 뉴스를 전하는 주간OSM이 {c.post_nr}번째 기사를
    발행했습니다! https://www.weeklyosm.eu/ko/archives/{c.url_nr}"
bluesky_text: "{c.tw_text}"
mail_body: |
    매주 일어나는 오픈스트리트맵 소식을 종합한,{c.post_nr}번째 주간OSM이 발행되었습니다.

    {c.url}

    읽어 주셔서 감사합니다!
    주간OSM에 올라갈 만한 소식을 알고 계시나요? 그렇다면 https://osmbc.openstreetmap.de/login 에서 오픈스트리트맵 계정으로 로그인만 하면 여
    러분도 기사를 쓸 수 있습니다. 기사 작성법 등의 정보는 https://www.weeklyosm.eu/this-news-should-be-in-weeklyosm 을 참조하세요.
    주간OSM이란?
    누가 만드나요?: https://wiki.openstreetmap.org/wiki/WeeklyOSM#Available_Languages
    어디서 만드나요?: https://umap.openstreetmap.fr/en/map/weeklyosm-is-currently-produced-in_56718#2/8.6/108.3
