lang: "cn"
runnable: True
#do_mail: False     # uncomment in order to ignore "--mail" for this language
#do_twitter: False  # uncomment in order to ignore "--twitter" for this language
#do_mastodon: False # uncomment in order to ignore "--mastodon" for this language
do_bluesky: False # comment to send an additional post in this language if "--bluesky" is called
do_josm: False # comment to send an additional josm wiki post in this language if "--josm" is called
mail_from: "weeklyteam <{c.mail_USER}>"
mail_subject: "weeklyOSM #{c.post_nr} {c.daterange_str}"
tw_text:
    "OSM周刊第{c.post_nr}期简体中文版现已发布！ 点击此处本周了解#openstreetmap
    #osm 社区的最新动态：https://www.weeklyosm.eu/cn/archives/{c.url_nr}"
bluesky_text: "{c.tw_text}"
mail_body: |
    OSM周刊第{c.post_nr}期简体中文版现已发布！点击下面的链接，了解本周OpenStreetMap社区最新动态：

    {c.url}

    p.s.: 你也可以使用OSM账号登陆 https://osmbc.openstreetmap.de/login ，为OSM周刊提供新闻素材。教程如下：https://www.weeklyosm.eu/this-news-should-be-in-weeklyosm 

    OSM周刊（weeklyOSM）是什么? 
    关于OSM周刊：https://wiki.openstreetmap.org/wiki/WeeklyOSM#Available_Languages 
    我们的编者来自五湖四海：https://umap.openstreetmap.fr/en/map/weeklyosm-is-currently-produced-in_56718#2/8.6/108.3

    祝好！
