lang: 'int'
url: "https://www.weeklyosm.eu/en/archives/{c.url_nr}/"
runnable: True
#do_mail: False     # uncomment in order to ignore "--mail" for this language
do_twitter: False   # comment to send an additional tweet in this language if "--twitter" is called (attention: shorten text to <280 chars!)
#do_mastodon: False # uncomment in order to ignore "--mastodon" for this language
#do_josm: False     # uncomment in order to ignore "--josm" for this language
do_pin_mastodon: True
do_unpin_mastodon: True

tw_text: "ğŸ‘‰ https://www.weeklyosm.eu/archives/{c.url_nr} ğŸ‘ˆ  Issue {c.post_nr} of weeklyOSM is out. ğŸŒ æ¶µè“‹ #é–‹æ”¾è¡—åœ– #osm ä¸–ç•Œå¤§å°äº‹çš„æ–°ä¸€æœŸ weeklyOSM å·²ç¶“ç™¼ä½ˆ ğŸš€ Lisez les derniÃ¨res nouvelles de l'univers #openstreetmap ğŸ—ºï¸ Viele Neuigkeiten aus der #osm Welt ğŸ“° æ–°ä¸€æœŸçš„OSMå‘¨åˆŠå·²ç»å‘å¸ƒ ğŸŒ Se ha publicado un nuevo nÃºmero del semanarioOSM ğŸŒ æœ€æ–°ã®é€±åˆŠOSMãŒç™ºè¡Œã•ã‚Œã¾ã—ãŸã€‚â›©ï¸  ì£¼ê°„OSM ìµœì‹ í˜¸ê°€ ë‚˜ì™”ìŠµë‹ˆë‹¤  ğŸ’¬ Ğ¢Ğ¸Ğ¶Ğ½ĞµĞ²Ğ¸Ğº OSM Ñ‚ĞµĞ¿ĞµÑ€ Ğ´Ğ¾ÑÑ‚ÑƒĞ¿Ğ½Ğ¸Ğ¹ Ğ£ĞºÑ€Ğ°Ñ—Ğ½ÑÑŒĞºĞ¾Ñ ğŸ“² @OpenStreetMap@a.gup.pe @openstreetmap@lemmy.ml"

mail_from: "weeklyteam <{c.mail_user}>"
mail_subject: 'weeklyOSM #{c.post_nr} {c.daterange_str}'
mail_body: | 
  The weekly round-up of OSM news, issue # {c.post_nr},
  is now available online, giving as always a summary of a lot of things happening in the openstreetmap world:
  
  https://www.weeklyosm.eu/archives/{c.url_nr}

  Enjoy! 

  Did you know that you can also submit messages for the weeklyOSM? Just log in to https://osmbc.openstreetmap.de/login with your OSM account. Read more about how to write a post here: https://www.weeklyosm.eu/this-news-should-be-in-weeklyosm 

  weeklyOSM? 
  who: https://wiki.openstreetmap.org/wiki/WeeklyOSM#Available_Languages 
  where?: https://umap.openstreetmap.fr/en/map/weeklyosm-is-currently-produced-in_56718#2/8.6/108.3
josm_body: | 
  en: * {c.publishdate_iso} **weeklyOSM**: The weekly round-up of OSM news, issue [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}], is now available.
  ca: * {c.publishdate_slash} **setmanalOSM** : El resum setmanal de notÃ­cies d'OSM, ja estÃ  disponible nÃºmero [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}]
  da: * {c.publishdate_dash} **weeklyOSM**: Den ugentlige opsummering af OSM-nyheder, nummer [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}], er nu tilgÃ¦ngelig
  de: * {c.publishdate_dot} **Wochennotiz**: Die wÃ¶chentliche Ausgabe der OSM-News [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}] ist nun verfÃ¼gbar
  es: * {c.publishdate_dash} **semanarioOSM** : El resumen semanario de noticias de OSM [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}], ya estÃ¡ disponible
  fr: * {c.publishdate_slash} **hebdoOSM**: Le rÃ©sumÃ© hebdomadaire [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}] de l'actualitÃ© OpenStreetMap vient de paraÃ®tre
  hu: * {c.publishdate_iso} **weeklyOSM**: Az OSM heti hÃ­rÃ¶sszefoglalÃ³jÃ¡nak [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr} rÃ©sze] mÃ¡r elÃ©rhetÅ‘ angolul.
  it: * {c.publishdate_dot} **Notiziario Settimanale OSM**: Il riepilogo settimanale [https://www.weeklyosm.eu/archives/{c.url_nr} N. {c.post_nr}]delle notizie su OSM Ã¨ adesso disponibile
  ko: * {c.publishdate_iso} **ì£¼ê°„OSM**: ì´ë²ˆ ì£¼ì˜ ì˜¤í”ˆìŠ¤íŠ¸ë¦¬íŠ¸ë§µ ê´€ë ¨ ì†Œì‹ì„ ì „í•´ì£¼ëŠ” ì£¼ê°„OSM [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}í˜¸]ê°€ ì˜¬ë¼ì™”ìŠµë‹ˆë‹¤
  lt: * {c.publishdate_iso} **weeklyOSM**: SavaitinÄ— OSM naujienÅ³ santrauka [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}] yra prieinama anglÅ³ kalba
  nl: * {c.publishdate_iso} **weeklyOSM**: De wekelijkse verzameling nieuws over OSM, uitgave [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}], is nu online beschikbaar in het Engels
  pl: * {c.publishdate_dot} **Tygodnik OSM**: [https://www.weeklyosm.eu/archives/{c.url_nr} nr {c.post_nr}] cotygodniowego podsumowania wiadomoÅ›ci ze Å›wiata OSM jest juÅ¼ dostÄ™pny.
  ru: * {c.publishdate_iso} **weeklyOSM**: ĞµĞ¶ĞµĞ½ĞµĞ´ĞµĞ»ÑŒĞ½Ñ‹Ğ¹ Ğ¾Ğ±Ğ·Ğ¾Ñ€ Ğ½Ğ¾Ğ²Ğ¾ÑÑ‚ĞµĞ¹ OSM, Ğ²Ñ‹Ğ¿ÑƒÑĞº [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}], Ğ´Ğ¾ÑÑ‚ÑƒĞ¿ĞµĞ½ Ğ¾Ğ½Ğ»Ğ°Ğ¹Ğ½ Ğ½Ğ° Ğ°Ğ½Ğ³Ğ»Ğ¸Ğ¹ÑĞºĞ¾Ğ¼ Ğ¸ Ğ½ĞµÑĞºĞ¾Ğ»ÑŒĞºĞ¸Ñ… Ğ´Ñ€ÑƒĞ³Ğ¸Ñ… ÑĞ·Ñ‹ĞºĞ°Ñ…
  sk: * {c.publishdate_iso} **weeklyOSM**: TÃ½Å¾dennÃ½ sumÃ¡r noviniek v OSM, vydanie [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}], je uÅ¾ dostupnÃ½ online v angliÄtine.
  sr@latin: * {c.publishdate_iso} **weeklyOSM**: Nedeljna tura vesti iz OSM sveta, problem zaveden pod brojem [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}], od sada je dostupna na engleskom jeziku
  uk: * {c.publishdate_dot} **weeklyOSM**: Ğ©Ğ¾Ñ‚Ğ¸Ğ¶Ğ½ĞµĞ²Ğ¸Ğ¹ Ğ¾Ğ³Ğ»ÑĞ´ Ğ½Ğ¾Ğ²Ğ¸Ğ½ OSM, Ğ²Ğ¸Ğ¿ÑƒÑĞº [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}], Ğ´Ğ¾ÑÑ‚ÑƒĞ¿Ğ½Ğ¸Ğ¹ Ğ°Ğ½Ğ³Ğ»Ñ–Ğ¹ÑÑŒĞºĞ¾Ñ Ñ‚Ğ° Ñ–Ğ½ÑˆĞ¸Ğ¼Ğ¸ Ğ¼Ğ¾Ğ²Ğ°Ğ¼Ğ¸
  zh_CN: * {c.publishdate_iso} **weeklyOSM**ï¼šä¸€å‘¨ä¸€æ¬¡çš„ OSM æ¶ˆæ¯æ±‡æŠ¥ï¼Œ[https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}]æœŸä¸­å›½åè¯­ç‰ˆæœ¬å·²ç»ä¸Šçº¿ã€‚
  zh_TW: * {c.publishdate_iso} **weeklyOSM**ï¼šä¸€é€±ä¸€æ¬¡çš„ OSM æ¶ˆæ¯å½™å ±ï¼Œ[https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}]æœŸå°ç£è¯èªç‰ˆæœ¬å·²ç¶“ä¸Šç·šã€‚
