lang: 'int'
url: "https://www.weeklyosm.eu/en/archives/{c.url_nr}/"
runnable: True
#do_mail: False     # uncomment in order to ignore "--mail" for this language
do_twitter: False   # comment to send an additional tweet in this language if "--twitter" is called (attention: shorten text to <280 chars!)
#do_mastodon: False # uncomment in order to ignore "--mastodon" for this language
#do_bluesky: True   # uncomment in order to ignore "--bluesky" for this language
#do_josm: False     # uncomment in order to ignore "--josm" for this language
do_pin_mastodon: True
do_unpin_mastodon: True

tw_text: "ğŸ‘‰ https://www.weeklyosm.eu/archives/{c.url_nr} ğŸ‘ˆ \n
Issue {c.post_nr} of #weeklyOSM is out. ğŸŒ \n
æ¶µè“‹ #é–‹æ”¾è¡—åœ– #osm ä¸–ç•Œå¤§å°äº‹çš„æ–°ä¸€æœŸ weeklyOSM å·²ç¶“ç™¼ä½ˆ ğŸš€ \n
Lisez les derniÃ¨res nouvelles de l'univers #openstreetmap ğŸ—ºï¸ \n
Viele Neuigkeiten aus der #osm Welt ğŸ“° \n
æ–°ä¸€æœŸçš„OSMå‘¨åˆŠå·²ç»å‘å¸ƒ ğŸŒ \n
Se ha publicado un nuevo nÃºmero del semanarioOSM ğŸŒ \n
æœ€æ–°ã®é€±åˆŠOSMãŒç™ºè¡Œã•ã‚Œã¾ã—ãŸã€‚â›©ï¸  \n
ì£¼ê°„OSM ìµœì‹ í˜¸ê°€ ë‚˜ì™”ìŠµë‹ˆë‹¤  ğŸ’¬ \n
Ğ¢Ğ¸Ğ¶Ğ½ĞµĞ²Ğ¸Ğº OSM Ñ‚ĞµĞ¿ĞµÑ€ Ğ´Ğ¾ÑÑ‚ÑƒĞ¿Ğ½Ğ¸Ğ¹ Ğ£ĞºÑ€Ğ°Ñ—Ğ½ÑÑŒĞºĞ¾Ñ ğŸ“² \n
@OpenStreetMap@a.gup.pe"

bluesky_text: "ğŸ‘‰ https://www.weeklyosm.eu/archives/{c.url_nr} ğŸ‘ˆ \n
Issue {c.post_nr} of #weeklyOSM is out. ğŸŒ \n
æ¶µè“‹ #é–‹æ”¾è¡—åœ– #osm ä¸–ç•Œå¤§å°äº‹çš„æ–°ä¸€æœŸ weeklyOSM å·²ç¶“ç™¼ä½ˆ ğŸš€ \n
Lisez les derniÃ¨res nouvelles de l'univers #openstreetmap ğŸ—ºï¸ \n
Viele Neuigkeiten aus der #osm Welt ğŸ“° \n
æ–°ä¸€æœŸçš„OSMå‘¨åˆŠå·²ç»å‘å¸ƒ ğŸŒ"

mail_from: "weeklyteam <{c.mail_USER}>"
mail_subject: 'weeklyOSM #{c.post_nr} {c.daterange_str}'
mail_body: | 
  The weekly round-up of OSM news, issue # {c.post_nr},
  is now available online, giving as always a summary of a lot of things happening in the openstreetmap world:
  
  https://www.weeklyosm.eu/archives/{c.url_nr}

  Enjoy! 

  Did you know that you can also submit messages for the weeklyOSM? Just log in to https://osmbc.openstreetmap.de/login with your OSM account. Read more about how to write a post here: https://www.weeklyosm.eu/this-news-should-be-in-weeklyosm 

  weeklyOSM? 
  who: https://wiki.openstreetmap.org/wiki/WeeklyOSM#Available_Languages 
  where?: https://umap.openstreetmap.fr/en/map/weeklyosm-is-currently-produced-in_56718#2/8.6/108.3
josm_body: | 
  en: * {c.publishdate_iso} **weeklyOSM**: The weekly round-up of OSM news, issue [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}], is now available.
  ar: * {c.publishdate_iso} **Ø£Ø³Ø¨ÙˆØ¹ÙŠOSM**: ÙŠØªÙˆÙØ± Ø§Ù„Ø¢Ù† Ø§Ù„Ù…Ù„Ø®Øµ Ø§Ù„Ø£Ø³Ø¨ÙˆØ¹ÙŠ Ù„Ø£Ø®Ø¨Ø§Ø± OSMØŒ Ø§Ù„Ø¹Ø¯Ø¯ [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}].
  ca: * {c.publishdate_slash} **setmanalOSM** : El resum setmanal de notÃ­cies d'OSM, ja estÃ  disponible nÃºmero [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}]
  cs: * {c.publishdate_iso} **weeklyOSM**: TÃ½dennÃ­ shrnutÃ­ novinek zÂ OSM, vydÃ¡nÃ­ [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}] je jiÅ¾ dostupnÃ©.
  da: * {c.publishdate_dash} **weeklyOSM**: Den ugentlige opsummering af OSM-nyheder, nummer [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}], er nu tilgÃ¦ngelig
  de: * {c.publishdate_dot} **Wochennotiz**: Die wÃ¶chentliche Ausgabe der OSM-News [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}] ist nun verfÃ¼gbar
  el: * {c.publishdate_iso} **weeklyOSM**: Î— ÎµÎ²Î´Î¿Î¼Î±Î´Î¹Î±Î¯Î± ÏƒÏÎ½Î¿ÏˆÎ· Ï„Ï‰Î½ ÎµÎ¹Î´Î®ÏƒÎµÏ‰Î½ Ï„Î¿Ï… OSM Î¼Îµ Ï„Î¿ Ï„ÎµÏÏ‡Î¿Ï‚ [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}] Î½Î± ÎµÎ¯Î½Î±Î¹ Ï€Î»Î­Î¿Î½ Î´Î¹Î±Î¸Î­ÏƒÎ¹Î¼Î¿
  eo: * {c.publishdate_iso} **weeklyOSM**: La semajna resumo de OSM-novaÄµoj, numero [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}], nun haveblas.
  es: * {c.publishdate_dash} **semanarioOSM** : El resumen semanario de noticias de OSM [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}], ya estÃ¡ disponible
  fi: * {c.publishdate_dot} **weeklyOSM**: Viikoittainen kooste OSM-uutisista, numero [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}] on nyt saatavilla.
  fo: * {c.publishdate_iso} **weeklyOSM**: Vikuliga samandrÃ¡ttur av OSM-tÃ­Ã°indum, ÃºtgÃ¡va [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}], er nÃº tÃ¸k.
  fr: * {c.publishdate_slash} **hebdoOSM**: Le rÃ©sumÃ© hebdomadaire [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}] de l'actualitÃ© OpenStreetMap vient de paraÃ®tre
  hu: * {c.publishdate_dotspace} **weeklyOSM**: Az OSM heti hÃ­rÃ¶sszefoglalÃ³jÃ¡nak [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr} rÃ©sze] mÃ¡r elÃ©rhetÅ‘ angolul.
  id: * {c.publishdate_slash} **weeklyOSM**: Kabar terkini seputar OSM, edisi [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}], bisa dibaca sekarang.
  is: * {c.publishdate_iso} **weeklyOSM**: Vikanleg yfirferÃ° yfir OSM frÃ©ttir, ÃºtgÃ¡fa [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}], er nÃº Ã­ boÃ°i.
  it: * {c.publishdate_dot} **Notiziario Settimanale OSM**: Il riepilogo settimanale [https://www.weeklyosm.eu/archives/{c.url_nr} N. {c.post_nr}] delle notizie su OSM Ã¨ adesso disponibile
  ja: * {c.publishdate_iso} **é€±åˆŠOSM**: OSMãƒ‹ãƒ¥ãƒ¼ã‚¹ã®1é€±é–“ç·ã¾ã¨ã‚ã€‚[https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}]ãŒå…¬é–‹ã•ã‚Œã¦ã„ã¾ã™ã€‚
  ko: * {c.publishdate_iso} **ì£¼ê°„OSM**: ì´ë²ˆ ì£¼ì˜ ì˜¤í”ˆìŠ¤íŠ¸ë¦¬íŠ¸ë§µ ê´€ë ¨ ì†Œì‹ì„ ì „í•´ì£¼ëŠ” ì£¼ê°„OSM [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}í˜¸]ê°€ ì˜¬ë¼ì™”ìŠµë‹ˆë‹¤
  lt: * {c.publishdate_iso} **weeklyOSM**: SavaitinÄ— OSM naujienÅ³ santrauka [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}] yra prieinama anglÅ³ kalba
  nb: * {c.publishdate_dot} **weeklyOSM**: Den ukentlige oppsummeringen av OSM-nyheter, utgave [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}], er nÃ¥ tilgjengelig.
  nl: * {c.publishdate_dash} **weeklyOSM**: De wekelijkse verzameling nieuws over OSM, uitgave [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}], is nu online beschikbaar in het Engels
  nn: * {c.publishdate_dot} **weeklyOSM**: Den vekelege oppsummeringa av OSM-nyhende, utgÃ¥ve [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}], er no tilgjengeleg.
  pl: * {c.publishdate_dot} **Tygodnik OSM**: [https://www.weeklyosm.eu/archives/{c.url_nr} nr {c.post_nr}] cotygodniowego podsumowania wiadomoÅ›ci ze Å›wiata OSM jest juÅ¼ dostÄ™pny.
  pt: * {c.publishdate_slash} **semanÃ¡rioOSM**: A ediÃ§Ã£o [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}] do resumo semanal de notÃ­cias do OSM estÃ¡ disponÃ­vel.
  pt_BR: * {c.publishdate_slash} **semanÃ¡rioOSM**: A ediÃ§Ã£o [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}] do resumo semanal de notÃ­cias do OSM estÃ¡ disponÃ­vel.
  ru: * {c.publishdate_dot} **weeklyOSM**: ĞµĞ¶ĞµĞ½ĞµĞ´ĞµĞ»ÑŒĞ½Ñ‹Ğ¹ Ğ¾Ğ±Ğ·Ğ¾Ñ€ Ğ½Ğ¾Ğ²Ğ¾ÑÑ‚ĞµĞ¹ OSM, Ğ²Ñ‹Ğ¿ÑƒÑĞº [https://www.weeklyosm.eu/archives/{c.url_nr} â„–{c.post_nr}], Ğ´Ğ¾ÑÑ‚ÑƒĞ¿ĞµĞ½ Ğ¾Ğ½Ğ»Ğ°Ğ¹Ğ½ Ğ½Ğ° Ğ°Ğ½Ğ³Ğ»Ğ¸Ğ¹ÑĞºĞ¾Ğ¼ Ğ¸ Ğ½ĞµÑĞºĞ¾Ğ»ÑŒĞºĞ¸Ñ… Ğ´Ñ€ÑƒĞ³Ğ¸Ñ… ÑĞ·Ñ‹ĞºĞ°Ñ…
  be: * {c.publishdate_dot} **weeklyOSM**: Ğ¨Ñ‚Ğ¾Ñ‚Ñ‹Ğ´Ğ½Ñ‘Ğ²Ñ‹ Ğ°Ğ³Ğ»ÑĞ´ Ğ½Ğ°Ğ²Ñ–Ğ½ OSM, Ğ²Ñ‹Ğ¿ÑƒÑĞº [https://www.weeklyosm.eu/archives/{c.url_nr} â„–{c.url_nr}], Ğ´Ğ°ÑÑ‚ÑƒĞ¿Ğ½Ñ‹ Ğ¾Ğ½Ğ»Ğ°Ğ¹Ğ½ Ğ½Ğ° Ğ°Ğ½Ğ³Ğ»Ñ–Ğ¹ÑĞºĞ°Ğ¹ Ñ– Ğ½ĞµĞºĞ°Ğ»ÑŒĞºÑ–Ñ… Ñ–Ğ½ÑˆÑ‹Ñ… Ğ¼Ğ¾Ğ²Ğ°Ñ…
  sk: * {c.publishdate_dot} **weeklyOSM**: TÃ½Å¾dennÃ½ sumÃ¡r noviniek v OSM, vydanie [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}], je uÅ¾ dostupnÃ½ online v angliÄtine.
  sr@latin: * {c.publishdate_dot} **weeklyOSM**: Nedeljna tura vesti iz OSM sveta, problem zaveden pod brojem [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}], od sada je dostupna na engleskom jeziku
  sv: * {c.publishdate_iso} **weeklyOSM**: Veckosammanfattningen av OSM-nyheter, nummer [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}], Ã¤r nu tillgÃ¤nglig.
  uk: * {c.publishdate_dot} **weeklyOSM**: Ğ©Ğ¾Ñ‚Ğ¸Ğ¶Ğ½ĞµĞ²Ğ¸Ğ¹ Ğ¾Ğ³Ğ»ÑĞ´ Ğ½Ğ¾Ğ²Ğ¸Ğ½ OSM, Ğ²Ğ¸Ğ¿ÑƒÑĞº [https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}], Ğ´Ğ¾ÑÑ‚ÑƒĞ¿Ğ½Ğ¸Ğ¹ Ğ°Ğ½Ğ³Ğ»Ñ–Ğ¹ÑÑŒĞºĞ¾Ñ Ñ‚Ğ° Ñ–Ğ½ÑˆĞ¸Ğ¼Ğ¸ Ğ¼Ğ¾Ğ²Ğ°Ğ¼Ğ¸
  zh_CN: * {c.publishdate_iso} **weeklyOSM**ï¼šä¸€å‘¨ä¸€æ¬¡çš„ OSM æ¶ˆæ¯æ±‡æŠ¥ï¼Œ[https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}]æœŸä¸­å›½åè¯­ç‰ˆæœ¬å·²ç»ä¸Šçº¿ã€‚
  zh_TW: * {c.publishdate_iso} **weeklyOSM**ï¼šä¸€é€±ä¸€æ¬¡çš„ OSM æ¶ˆæ¯å½™å ±ï¼Œ[https://www.weeklyosm.eu/archives/{c.url_nr} #{c.post_nr}]æœŸå°ç£è¯èªç‰ˆæœ¬å·²ç¶“ä¸Šç·šã€‚
