lang: 'pl'
runnable: True
#do_mail: False    # uncomment in order to ignore "--mail" for this language
#do_twitter: False # uncomment in order to ignore "--twitter" for this language
do_mastodon: False # comment to send an additional toot in this language if "--mastodon" is called
mail_from: "weeklyteam <{c.mail_user}>"
mail_subject: 'weeklyOSM #{c.post_nr} {c.daterange_str}'
tw_text: "Wydanie {c.post_nr} Tygodnika OSM już teraz dostępne w języku polskim! Najnowsze wieści ze świata #openstreetmap #osm https://www.weeklyosm.eu/pl/archives/{c.url_nr}"
mail_to: 
  - "you could enter emails directly here, but it can/will"
  - "be overwritten by content from mailto/weekly_en.yaml"
mail_body: | 
  Wydanie #{c.post_nr} cotygodniowego przeglądu wiadomości 
  OSM, zawierające podsumowanie wielu rzeczy, które dzieją 
  się w świecie OpenStreetMap, jest już dostępne w języku 
  polskim:
  
   {c.url}

  Miłej lektury! 

  Czy wiesz, że możesz samodzielnie przesyłać wiadomości do zamieszczenia na łamach Tygodnika OSM? Zaloguj się do https://osmbc.openstreetmap.de/login przy użyciu swojego konta OSM. Aby dowiedzieć się więcej na temat tego jak napisać własny post, przeczytaj ten poradnik: https://www.weeklyosm.eu/this-news-should-be-in-weeklyosm

  Tygodnik OSM? 
  Kto? https://wiki.openstreetmap.org/wiki/WeeklyOSM#Available_Languages 
  Gdzie? https://umap.openstreetmap.fr/en/map/weeklyosm-is-currently-produced-in_56718#2/8.6/108.3
