lang: 'int'
url: "https://www.weeklyosm.eu/en/archives/{c.url_nr}/"
runnable: True
#do_mail: False     # uncomment in order to ignore "--mail" for this language
do_twitter: False   # comment to send an additional tweet in this language if "--twitter" is called (attention: shorten text to <280 chars!)
#do_mastodon: False # uncomment in order to ignore "--mastodon" for this language
do_pin_mastodon: True
do_unpin_mastodon: True

tw_text: "ðŸ‘‰ https://www.weeklyosm.eu/archives/{c.url_nr} ðŸ‘ˆ  Issue {c.post_nr} of weeklyOSM is out. ðŸŒ æ¶µè“‹ #é–‹æ”¾è¡—åœ– #osm ä¸–ç•Œå¤§å°äº‹çš„æ–°ä¸€æœŸ weeklyOSM å·²ç¶“ç™¼ä½ˆ ðŸš€ Lisez les derniÃ¨res nouvelles de l'univers #openstreetmap ðŸ—ºï¸ Viele Neuigkeiten aus der #osm Welt ðŸ“° æ–°ä¸€æœŸçš„OSMå‘¨åˆŠå·²ç»å‘å¸ƒ ðŸŒ Se ha publicado un nuevo nÃºmero del semanarioOSM ðŸŒ æœ€æ–°ã®é€±åˆŠOSMãŒç™ºè¡Œã•ã‚Œã¾ã—ãŸã€‚â›©ï¸  ì£¼ê°„OSM ìµœì‹ í˜¸ê°€ ë‚˜ì™”ìŠµë‹ˆë‹¤  ðŸ’¬ Ð¢Ð¸Ð¶Ð½ÐµÐ²Ð¸Ðº OSM Ñ‚ÐµÐ¿ÐµÑ€ Ð´Ð¾ÑÑ‚ÑƒÐ¿Ð½Ð¸Ð¹ Ð£ÐºÑ€Ð°Ñ—Ð½ÑÑŒÐºÐ¾ÑŽ ðŸ“² ðŸ‘‰ https://www.weeklyosm.eu/archives/{c.url_nr} ðŸ‘ˆ "

mail_from: "weeklyteam <{c.mail_user}>"
mail_subject: 'weeklyOSM #{c.post_nr} {c.daterange_str}'
mail_body: | 
  The weekly round-up of OSM news, issue # {c.post_nr},
  is now available online, giving as always a summary of a lot of things happening in the openstreetmap world:
  
  https://www.weeklyosm.eu/archives/{c.url_nr}

  Enjoy! 

  Did you know that you can also submit messages for the weeklyOSM? Just log in to https://osmbc.openstreetmap.de/login with your OSM account. Read more about how to write a post here: https://www.weeklyosm.eu/this-news-should-be-in-weeklyosm 

  weeklyOSM? 
  who: https://wiki.openstreetmap.org/wiki/WeeklyOSM#Available_Languages 
  where?: https://umap.openstreetmap.fr/en/map/weeklyosm-is-currently-produced-in_56718#2/8.6/108.3
